use_frameworks!

target 'InStatEventlistView_Example' do
  pod 'InStatEventlistView', :path => '../'
	pod 'InStatDownloadButton'

  target 'InStatEventlistView_Tests' do
    inherit! :search_paths

    
  end
end
